/**
 * Offline drug-name list for the non-DM "home medications" autocomplete.
 * Sources, merged and deduped:
 *   1. SFDA Essential Medicines List of Saudi Arabia 2023 (official national
 *      essential formulary; authoritative). Multi-line combination-vaccine
 *      names were dropped during extraction.
 *   2. A curated set of common outpatient generic (INN) names, to cover
 *      everyday drugs the essential list represents by a single class member
 *      (e.g. simvastatin, omeprazole, bisoprolol, empagliflozin).
 * Generic names only (not every brand/strength/registered product). The tool
 * stays fully offline — nothing is transmitted. The combobox prefix-filters
 * this list; free text is always allowed for anything not listed.
 */
const RAW = [
  "Abacavir",
  "Abiraterone acetate",
  "Acarbose",
  "Acetaminophen",
  "Acetazolamide",
  "Acetylcysteine",
  "Acetylsalicylic acid",
  "Acyclovir",
  "Acyclovir (Aciclovir)",
  "Adalimumab",
  "Adenosine",
  "Albuterol",
  "Alectinib",
  "Alendronate",
  "Alfuzosin",
  "Aliskiren",
  "Allopurinol",
  "Alogliptin",
  "Alprazolam",
  "Alprostadil (Prostaglandin E1)",
  "Alteplase",
  "Amikacin",
  "Amiloride",
  "Amiodarone",
  "Amitriptyline",
  "Amlodipine",
  "Amoxicillin",
  "Amoxicillin-clavulanate",
  "Amoxicillin/clavulanic acid",
  "Amphotericin-B",
  "Ampicillin",
  "Anastrozole",
  "Anidulafungin",
  "Anti-human thymocyte immunoglobulin",
  "Anti-Thymocyte Globulin",
  "Apixaban",
  "Apomorphine",
  "Aripiprazole",
  "Aspirin",
  "Atazanavir",
  "Atenolol",
  "Atomoxetine",
  "Atorvastatin",
  "Atovaquone-proguanil",
  "Atropine sulphate",
  "Azacitidine",
  "Azathioprine",
  "Azelastine",
  "Azithromycin",
  "Baclofen",
  "BCG Vaccine",
  "Beclomethasone",
  "Beclomethasone dipropionate",
  "Benazepril",
  "Bendamustine hydrochloride",
  "Benzathine benzylpenicillin",
  "Benztropine",
  "Beractant",
  "Betamethasone",
  "Betamethasone dipropionate",
  "Bicalutamide",
  "Bictegravir/emtricitabine/tenofovir",
  "Bimatoprost",
  "Bisacodyl",
  "Bisoprolol",
  "Bleomycin hydrochloride",
  "Blinatumomab",
  "Bortezomib",
  "Brimonidine",
  "Brimonidine tartrate",
  "Bromocriptine",
  "Budesonide",
  "Bumetanide",
  "Bupivacaine hydrochloride",
  "Buprenorphine",
  "Bupropion",
  "Buspirone",
  "Busulfan",
  "Cabergoline",
  "Caffeine citrate",
  "Calcitonin salmon",
  "Calcium carbonate",
  "Calcium gluconate",
  "Canagliflozin",
  "Candesartan",
  "Capecitabine",
  "Captopril",
  "Carbamazepine",
  "Carbidopa-levodopa",
  "Carbimazole",
  "Carboplatin",
  "Carmustine",
  "Carvedilol",
  "Cefalexin",
  "Cefazolin",
  "Cefdinir",
  "Cefixime",
  "Cefpodoxime",
  "Ceftazidime",
  "Ceftazidime/avibactam",
  "Ceftolozane/tazobactam",
  "Ceftriaxone",
  "Cefuroxime",
  "Celecoxib",
  "Cephalexin",
  "Certolizumab pegol",
  "Cetirizine",
  "Chlorambucil",
  "Chloramphenicol",
  "Chloroquine phosphate",
  "Chlorthalidone",
  "Cholecalciferol",
  "Ciclosporin",
  "Ciprofloxacin",
  "Cisatracurium",
  "Cisplatin",
  "Citalopram",
  "Clarithromycin",
  "Clindamycin",
  "Clobazam",
  "Clobetasol",
  "Clofarabine",
  "Clomifene",
  "Clomipramine",
  "Clonazepam",
  "Clonidine",
  "Clopidogrel",
  "Clotrimazole",
  "Cloxacillin",
  "Clozapine",
  "Coagulation factor IX",
  "Coagulation factor VIII",
  "Codeine",
  "Colchicine",
  "Colecalciferol",
  "Colistin (Colistimethate sodium)",
  "Crizotinib",
  "Cyanocobalamin",
  "Cyclobenzaprine",
  "Cyclopentolate",
  "Cyclophosphamide",
  "Cyclosporine",
  "Cytarabine",
  "Dabigatran",
  "Dacarbazine",
  "Daclatasvir",
  "Dapagliflozin",
  "Daratumumab",
  "Darbepoetin Alfa",
  "Darunavir",
  "Dasatinib",
  "Deferoxamine",
  "Desloratadine",
  "Desmopressin",
  "Desogestrel",
  "Desvenlafaxine",
  "Dexamethasone",
  "Dexlansoprazole",
  "Dexmedetomidine",
  "Dextroamphetamine",
  "Dextrose",
  "Dextrose with sodium chloride",
  "Diazepam",
  "Diclofenac",
  "Dicyclomine",
  "Digoxin",
  "Diltiazem",
  "Diphenhydramine",
  "Diphtheria, Tetanus, Acellular Pertussis (DTaP)",
  "Divalproex",
  "Dobutamine",
  "Docetaxel",
  "Docusate",
  "Docusate sodium/sennosides",
  "Dolutegravir",
  "Donepezil",
  "Dopamine hydrochloride",
  "Dorzolamide",
  "Doxazosin",
  "Doxepin",
  "Doxorubicin (as pegylated liposomal)",
  "Doxorubicin hydrochloride",
  "Doxycycline",
  "Dulaglutide",
  "Duloxetine",
  "Dutasteride",
  "Eletriptan",
  "Empagliflozin",
  "Emtricitabine/tenofovir alafenamide",
  "Enalapril",
  "Enalapril maleate",
  "Enoxaparin",
  "Entecavir",
  "Epinephrine",
  "Ergocalciferol",
  "Erlotinib",
  "Ertugliflozin",
  "Erythromycin",
  "Escitalopram",
  "Esomeprazole",
  "Estradiol",
  "Eszopiclone",
  "Etanercept",
  "Ethinyl estradiol",
  "Ethinylestradiol and desogestrel",
  "Ethinylestradiol/Drospirenone",
  "Ethinylestradiol/Levonorgestrel",
  "Ethionamide",
  "Etoposide",
  "Exenatide",
  "Ezetimibe",
  "Famciclovir",
  "Famotidine",
  "Febuxostat",
  "Felodipine",
  "Fenofibrate",
  "Fentanyl",
  "Ferrous sulfate",
  "Fexofenadine",
  "Filgrastim (G-CSF)",
  "Finasteride",
  "Flecainide",
  "Fluconazole",
  "Fludarabine phosphate",
  "Flumazenil",
  "Fluorescein sodium",
  "Fluorometholone",
  "Fluorouracil",
  "Fluoxetine",
  "Fluticasone",
  "Fluticasone propionate",
  "Fluticasone Propionate/Salmeterol",
  "Fluvastatin",
  "Folic acid",
  "Folinic acid",
  "Fondaparinux",
  "Formoterol",
  "Foscarnet",
  "Furosemide",
  "Gabapentin",
  "Galantamine",
  "Gemcitabine",
  "Gemfibrozil",
  "Gentamicin",
  "Glargine",
  "Gliclazide",
  "Glimepiride",
  "Glipizide",
  "Glucagon",
  "Glyburide",
  "Granisetron",
  "Guaifenesin",
  "Guanfacine",
  "Haemophilus Influenzae Type B (DTP-HepB-Hib)",
  "Haemophilus Influenzae Type B (DTPa-Hib-IPV)",
  "Haloperidol",
  "Heparin",
  "Hepatitis A Vaccine",
  "Hepatitis B Immunoglobulin",
  "Hepatitis B Vaccine",
  "Human Papilloma Virus vaccine",
  "Hydralazine",
  "Hydrochlorothiazide",
  "Hydrocortisone",
  "Hydrocortisone sodium succinate",
  "Hydromorphone",
  "Hydroxycarbamide",
  "Hydroxychloroquine",
  "Hydroxychloroquine Sulfate",
  "Hydroxychloroquine sulphate",
  "Hydroxyzine",
  "Hyoscyamine",
  "Ibandronate",
  "Ibrutinib",
  "Ibuprofen",
  "Idarucizumab",
  "Ifosfamide",
  "Imatinib mesilate",
  "Indapamide",
  "Indomethacin",
  "Influenza Vaccine (seasonal)",
  "Insulin Aspart",
  "Insulin degludec",
  "Insulin detemir",
  "Insulin glargine",
  "Insulin Lispro",
  "Iohexol",
  "Ipratropium",
  "Ipratropium bromide",
  "Irbesartan",
  "Irinotecan",
  "Isoflurane",
  "Isoniazid",
  "Isophane insulin",
  "Isosorbide dinitrate",
  "Isosorbide mononitrate",
  "Isotretinoin",
  "Itraconazole",
  "Ketamine",
  "Ketoconazole",
  "Ketorolac",
  "Labetalol",
  "Lactated ringer",
  "Lamivudine",
  "Lamotrigine",
  "Lansoprazole",
  "Latanoprost",
  "Ledipasvir/sofosbuvir",
  "Leflunomide",
  "Lenalidomide",
  "Letrozole",
  "Leuprorelin",
  "Levalbuterol",
  "Levetiracetam",
  "Levocetirizine",
  "Levodopa/Carbidopa/Entacapone",
  "Levofloxacin",
  "Levonorgestrel",
  "Levothyroxine",
  "Levothyroxine sodium",
  "Lidocaine hydrochloride",
  "Lidocaine hydrochloride/Dextrose",
  "Lidocaine hydrochloride/Epinephrine",
  "Linagliptin",
  "Linezolid",
  "Liothyronine",
  "Liraglutide",
  "Lisdexamfetamine",
  "Lisinopril",
  "Lithium",
  "Lithium carbonate",
  "Loperamide",
  "Lopinavir / Ritonavir",
  "Loratadine",
  "Lorazepam",
  "Losartan",
  "Losartan potassium",
  "Lovastatin",
  "Lurasidone",
  "Magnesium sulfate",
  "Measles, Mumps, Rubella (MMR) Vaccine",
  "Measles, Mumps, Rubella, Varicella (MMRV) Vaccine",
  "Mebendazole",
  "Meclizine",
  "Medroxyprogesterone",
  "Medroxyprogesterone acetate",
  "Mefloquine",
  "Meloxicam",
  "Memantine",
  "Meningococcal Meningitis Vaccine",
  "Mercaptopurine",
  "Meropenem",
  "Mesalamine",
  "Mesalazine",
  "MESNA",
  "Metformin",
  "Methadone",
  "Methimazole",
  "Methocarbamol",
  "Methotrexate",
  "Methyldopa",
  "Methylphenidate",
  "Methylprednisolone",
  "Methylthioninium chloride (Proveblue)",
  "Metoclopramide",
  "Metolazone",
  "Metoprolol",
  "Metoprolol succinate",
  "Metoprolol tartrate",
  "Metronidazole",
  "Miconazole",
  "Midazolam",
  "Midodrine",
  "Milrinone",
  "Minocycline",
  "Mirabegron",
  "Mirtazapine",
  "Mitoxantrone",
  "Mometasone",
  "Mometasone furoate",
  "Montelukast",
  "Morphine",
  "Morphine sulphate",
  "Moxifloxacin",
  "Mupirocin",
  "Mycophenolate",
  "Nadolol",
  "Naproxen",
  "Nateglinide",
  "Nebivolol",
  "Neostigmine methylsulfate",
  "Nifedipine",
  "Nilotinib",
  "Nitrofurantoin",
  "Nitroglycerin",
  "Nivolumab",
  "Norepinephrine",
  "Norethisterone",
  "Normal human immunoglobulin",
  "Nortriptyline",
  "Nystatin",
  "Ofloxacin",
  "Olanzapine",
  "Olaparib",
  "Olmesartan",
  "Omeprazole",
  "Ondansetron",
  "Oseltamivir",
  "Osimertinib",
  "Oxaliplatin",
  "Oxcarbazepine",
  "Oxybuprocaine hydrochloride",
  "Oxybutynin",
  "Oxycodone",
  "Oxycodone hydrochloride",
  "Oxytocin",
  "Paclitaxel",
  "Pantoprazole",
  "Paracetamol",
  "Paracetamol/caffeine citrate/codeine",
  "Paroxetine",
  "Pegaspargase",
  "Pembrolizumab",
  "Penicillin V",
  "Phenazopyridine",
  "Phenylephrine hydrochloride",
  "Phenytoin",
  "Phytomenadione (vit. K)",
  "Pilocarpine hydrochloride",
  "Pioglitazone",
  "Piperacillin/tazobactam",
  "Pneumococcal Polysaccharide Conjugated (PCV)",
  "Pneumococcal Polysaccharide Vaccine (PPSV23)",
  "Polyethylene glycol",
  "Ponatinib",
  "Potassium acetate",
  "Potassium chloride",
  "Potassium iodide",
  "Pramipexole",
  "Pravastatin",
  "Praziquantel",
  "Prazosin",
  "Prednisolone",
  "Prednisone",
  "Pregabalin",
  "Primidone",
  "Prochlorperazine",
  "Progesterone",
  "Promethazine",
  "Propofol",
  "Propranolol",
  "Protamine sulfate",
  "Prothrombin complex concentrates",
  "Pseudoephedrine",
  "Pyrazinamide",
  "Pyridoxine",
  "Quetiapine",
  "Quinapril",
  "Rabeprazole",
  "Raloxifene",
  "Ramipril",
  "Ranolazine",
  "Rasagiline",
  "Rasburicase",
  "Repaglinide",
  "Ribavirin",
  "Rifampicin",
  "Risedronate",
  "Risperidone",
  "Rituximab",
  "Rivaroxaban",
  "Rivastigmine",
  "Rizatriptan",
  "Ropinirole",
  "Rosuvastatin",
  "Rotavirus Vaccine",
  "Sacubitril-valsartan",
  "Salbutamol",
  "Salmeterol",
  "Saxagliptin",
  "Selegiline",
  "Semaglutide",
  "Senna",
  "Sertraline",
  "Sevoflurane",
  "Sildenafil",
  "Simvastatin",
  "Sitagliptin",
  "Sodium Bicarbonate",
  "Sodium chloride",
  "Sodium Phenylacetate/Sodium Benzoate",
  "Sofosbuvir",
  "Solifenacin",
  "Sorafenib",
  "Spironolactone",
  "Sucralfate",
  "Sugammadex",
  "Sulfamethoxazole + trimethoprim",
  "Sulfamethoxazole-trimethoprim",
  "Sulfasalazine",
  "Sumatriptan",
  "Suxamethonium chloride",
  "Tacrolimus",
  "Tadalafil",
  "Tamoxifen",
  "Tamsulosin",
  "Telmisartan",
  "Temozolomide",
  "Tenofovir disoproxil",
  "Terazosin",
  "Terbinafine",
  "Testosterone",
  "Tetanus Toxoid",
  "Tetracaine hydrochloride",
  "Tetracycline",
  "Theophylline",
  "Thiamine",
  "Thiotepa",
  "Ticagrelor",
  "Timolol",
  "Timolol maleate",
  "Tiotropium",
  "Tirofiban",
  "Tirzepatide",
  "Tizanidine",
  "Tolterodine",
  "Topiramate",
  "Torsemide",
  "Tramadol",
  "Tranexamic acid",
  "Trastuzumab",
  "Trazodone",
  "Triamcinolone",
  "Triamterene",
  "Trimethoprim",
  "Tropicamide",
  "Umeclidinium",
  "Valacyclovir",
  "Valganciclovir",
  "Valproate sodium",
  "Valproic acid",
  "Valsartan",
  "Vancomycin",
  "Vardenafil",
  "Vasopressin",
  "Venetoclax",
  "Venlafaxine",
  "Verapamil",
  "Verapamil hydrochloride",
  "Vigabatrin",
  "Vinblastine Sulfate",
  "Vincristine",
  "Vinorelbine",
  "Vitamin D",
  "Voriconazole",
  "Warfarin",
  "Xylometazoline hydrochloride",
  "Zidovudine",
  "Zoledronic acid",
  "Zolpidem",
  "Zonisamide",
];

export const DRUG_NAMES = Array.from(new Set(RAW.map((s) => s.trim()).filter(Boolean))).sort((a, b) =>
  a.localeCompare(b, "en", { sensitivity: "base" })
);
